language: objective-c

notifications:
    email:
        - hazem.khaled@gmail.com

env:
  matrix:
    - PLATFORM="ios"
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    # The BuildTools version used by your project
    - build-tools-21.0.1

    # Additional components
    - extra-google-google_play_services
    - addon-google_apis-google-21

install:
    - wget -q http://dl.google.com/android/ndk/android-ndk-r10e-darwin-x86_64.bin
    - chmod a+x android-ndk-r10e-linux-x86_64.bin
    - ./android-ndk-r10e-linux-x86_64.bin
    - mv android-ndk-r10e android-ndk

    - npm install -g tisdk titanium alloy
    - tisdk build 5.0.2.GA
    - ti sdk select latest

script:
    - ti build -p android -T dist-playstore -K packaging/android.keystore -P appcelerator -L helloworld -O build
