language: objective-c

notifications:
    email:
        - hazem.khaled@gmail.com
env:
    matrix:
        - PLATFORM="ios"
        - PLATFORM="android" ANDROID_VERSION="21"

before_install:
    - export ANDROID_HOME=$PWD/android-sdk-macosx
    - export ANDROID_SDK=$ANDROID_HOME
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

install:
    - npm install -g tisdk titanium alloy tishadow gulp
    - npm install gulp underscore moment gulp-util xml2js cloudinary
    - tisdk install 5.0.2.GA

    - gulp 'install:android_sdk'

before_script:
    - gulp 'start:emulator'
    - gulp 'config:tiapp' --test

script:
    - gulp 'test:calabash'
    - gulp 'test:jasmine'
